version: "3.8"

services:
  python-app:
    build:
      context: ./my-python-app
    ports:
      - "5001:5001"
    networks:
      - app-network

  react-app:
    build:
      context: ./my-react-app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
